services:
  jenkins-agent:
    platform: linux/x86_64
    build:
      context: .
    restart: unless-stopped
    privileged: true
    environment:
      # Jenkins masterとagentを同じマシン上で実行する場合はDocker networks経由で以下のように設定
      # - JENKINS_URL=http://jenkins-master:8080
      # Jenkins masterとagentを異なるマシン上で実行する場合は以下のように設定
      # - JENKINS_URL=http://<jenkins-master-ip>:8080
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
      # Jenkins masterのagent登録画面で発行したシークレットを設定
      - JENKINS_SECRET=${JENKINS_SECRET}
    volumes:
      - jenkins_agent_workspace:/workspace
      - ./network.lic:/licenses/network.lic
    networks:
      - jenkins-net

volumes:
  jenkins_agent_workspace:

networks:
  jenkins-net:
    external: true