services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_master_home:/var/jenkins_home
    networks:
      - jenkins-net

volumes:
  jenkins_master_home:

networks:
  jenkins-net:
    driver: bridge
    name: jenkins-net